language: python
dist: focal
cache: pip
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy2
    - pypy3
install:
    - pip install coveralls coverage
    - pip install -e ".[test]"
script:
    - coverage run -m zope.testrunner --test-path=src -pvc
after_success:
    - coveralls
notifications:
    email: false
