language: python
sudo: false
cache: pip
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install coveralls coverage
    - pip install -e ".[test]"
script:
    - coverage run -m zope.testrunner --test-path=src -pvc
after_success:
    - coveralls
notifications:
    email: false
